# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/mle-prep',
                'doc_host': 'https://vempaliakhil96.github.io',
                'git_url': 'https://github.com/vempaliakhil96/mle-prep',
                'lib_path': 'mle_prep'},
  'syms': {}}
